{% set name = "r-rgcca" %}
{% set version = "2.3" %}
{% set r_version = "4" %}
{% set build = "005" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    git_rev: {{ version }}
    git_url: https://github.com/rgcca-factory/RGCCA.git
    git_depth: 1

build:
    noarch: generic
    number: {{ build }}
    rpaths:
        - lib/
        - lib/R/lib/
    string: r3{{ r_version }}_{{ build }}
    include_recipe: False

requirements:
    build:
        - _r-mutex
        - r-base=3.5
        - r-deriv
        - r-devtools
        - r-mass
        - r-ggplot2
        - r-optparse
        - r-scales
        - r-igraph
        - r-ggrepel
        - r-plotly
        - r-visnetwork
        - r-vegan
        - r-gridextra
        - r-nnet
        - libgfortran
    run:
        - r-base >=3.{{ r_version }},<=3.6
        - r-deriv
        - r-devtools
        - r-mass
        - r-ggplot2
        - r-optparse
        - r-scales
        - r-igraph
        - r-ggrepel
        - r-plotly
        - r-visnetwork
        - r-vegan
        - r-gridextra
        - r-nnet

test:
    commands:
#       - echo $R
       # - $R -e "library('RGCCA')"
        - cd ${PREFIX} && Rscript launcher.R -h

about:
    home: https://CRAN.R-project.org/package=RGCCA
    doc_url: https://github.com/rgcca-factory/RGCCA/blob/master/README.mdh
    dev_url: https://github.com/rgcca-factory/RGCCA
    license: GPL (>= 2)
    license_family: GPL3
    summary: 'Multiblock data analysis concerns the analysis of several sets of variables
        (blocks) observed on the same group of individuals. The main aims of the RGCCA
        package are: (i) to study the relationships between blocks and (ii) to identify
        subsets of variables of each block which are active in their relationships
        with the other blocks.'

extra:
    copy_test_source_files: false
    final: true
    recipe-maintainers:
        - ecamenen